# Oficina 5.2

Nessa aula, você aprendeu que o TensorFlow é uma das bibliotecas de código aberto mais versáteis para a construção de Redes Neurais, possuindo um suporte para as diversas arquiteturas de redes. Então, a partir desse conhecimento adquirido, nessa oficina, você praticará a construção de uma rede neural, que vai classificar um conjunto de dígitos escritos à mão, conhecido como mnist. Para que seja possível a realização desses novos aprendizados, é fundamental que você:

Baixe o arquivo através do link “Oficina - TensorFlow.ipynb” e carregue-o no ambiente do Jupyter notebook;
Siga as seguintes instruções contidas no arquivo e aplique o que você aprendeu, para classificar corretamente o conjunto de dados, usando as bibliotecas TensorFlow e Keras:
“Treine uma rede neural com uma camada intermediária de 50 neurônios, utilizando o Keras e o TensorFlow sobre os dados contidos na variável train_images e usando os rótulos train_labels. Após construído o modelo, apresente a acurácia do projeto sobre os dados de teste (test_images, test_labels)”;

Identifique a acurácia obtida, ao executar o modelo, sobre um conjunto de dados de teste;
Por fim, exporte o arquivo do notebook e envie-o para a oficina da Aula 5.2 de Machine Learning.

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [10]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [11]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(50, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 50)                39250     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                510       
Total params: 39,760
Trainable params: 39,760
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [13]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.6483 - accuracy: 0.5440
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7432 - accuracy: 0.7438
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.6303 - accuracy: 0.7722
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5744 - accuracy: 0.7920
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5338 - accuracy: 0.8076


In [14]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 1ms/step - loss: 0.5438 - accuracy: 0.8027
Test accuracy: 0.8026999831199646


In [15]:
predictions = model.predict(test_images)

In [16]:
predictions[0]

array([1.7315554e-06, 3.0384410e-08, 9.1357715e-06, 1.1776497e-05,
       4.2056177e-05, 1.9181740e-01, 4.3067885e-05, 3.6341095e-01,
       9.9252397e-03, 4.3473864e-01], dtype=float32)

In [17]:
np.argmax(predictions[0])

9

In [18]:
test_labels[0]

9

In [19]:
img = test_images[0]

print(img.shape)

(28, 28)


In [20]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [21]:
predictions_single = model.predict(img)

print(predictions_single)

[[1.7315516e-06 3.0384403e-08 9.1357597e-06 1.1776505e-05 4.2056170e-05
  1.9181737e-01 4.3067874e-05 3.6341107e-01 9.9252369e-03 4.3473855e-01]]


In [22]:
np.argmax(predictions_single[0])

9

Desenvolvido por **Pâmella Araújo Balcaçar**, Rondonópolis-MT, 26/03/2021.